### PR TITLE
Fix Deprecated Sequence Warnings

### PR DESCRIPTION
**Pull request by goharattiq**
What does it do?
Convert regular strings to raw strings.

Why is it needed?
`isCrawler` throwing deprecated sequence warnings

Screenshot 2023-07-15 at 11 13 58 AM

### CODE REVIEW

**Comment by goharattiq** [comment]
@moskrc Would you please create a tag as well?

**Comment by moskrc** [comment]
done
https://github.com/moskrc/crawlerdetect/releases/tag/0.1.6

**Comment by goharattiq** [comment]
> done https://github.com/moskrc/crawlerdetect/releases/tag/0.1.6

Thank you so much

**Comment by goharattiq** [comment]
> done https://github.com/moskrc/crawlerdetect/releases/tag/0.1.6

If possible please publish `0.1.6`on PyPi as well.

**Comment by moskrc** [comment]
> If possible please publish `0.1.6`on PyPi as well.

Ouh, you are right! Done https://pypi.org/project/crawlerdetect/0.1.6/

**Pull request merged**
